### ISSUE TITLE
Regarding the building resource in `Package.swift`

### ISSUE THREAD

**Issue by FlickerSoul** [apple/swift-llvm-bindings#30]
It looks like the module map file is usually referenced as `<llvm_root>/llvm/include/module.modulemap` and the line 17 in the `Package.swift` doesn't seem to locate the module map correctly. That is, the `llvmModuleMapPath` is resolved as `<llvm_root>/llvm/include/llvm/module.modulemap` and doesn't match where the module map usually is.

```swift
    guard let llvmHeaderPath = env["SWIFT_LLVM_BINDINGS_PATH_TO_LLVM_HEADERS"] else {
        print("please pass an environment variable to swift-package: " +
              "SWIFT_LLVM_BINDINGS_PATH_TO_LLVM_HEADERS " +
              "(e.g. swift/llvm-project/llvm/include)")
        return nil
    }
    let llvmModuleMapPath = "\(llvmHeaderPath)/llvm/module.modulemap". // line 17
```

I am quite new to LLVM and am very likely to be wrong. If without `llvm` is intended, I can open a pr to fix it. :)

**Comment by egorzhdan** [comment]
@FlickerSoul sorry for a delayed reply!

You are correct, the modulemap was moved to a different path in the LLVM repo in https://github.com/llvm/llvm-project/commit/24f36a215b4eabd1d0e4abcce0c9277085d88a96 but we haven't updated the paths in Package.swift.

> If without llvm is intended, I can open a pr to fix it. :)

That would be appreciated, thanks!

**Comment by FlickerSoul** [comment]
> @FlickerSoul sorry for a delayed reply!
> 
> 
> 
> You are correct, the modulemap was moved to a different path in the LLVM repo in https://github.com/llvm/llvm-project/commit/24f36a215b4eabd1d0e4abcce0c9277085d88a96 but we haven't updated the paths in Package.swift.
> 
> 
> 
> > If without llvm is intended, I can open a pr to fix it. :)
> 
> 
> 
> That would be appreciated, thanks!

Thank you for confirming that! I'll open a PR soon! :)
