### ISSUE TITLE
Modules not found when used as a SwiftPM dependency

### ISSUE THREAD

**Issue by WowbaggersLiquidLunch** [apple/swift-llvm-bindings#32]
I'm able to build the project standalone using SwiftPM with no problems (or at least I think there is no problem). However, when I use it as a dependency, SwiftPM reports errors of missing modules.

When I build the depending package like this on the command line,

```
SWIFT_LLVM_BINDINGS_PATH_TO_LLVM_HEADERS=/path/to/LLVM/headers SWIFT_LLVM_BINDINGS_PATH_TO_LLVM_GENERATED_HEADERS=/path/to/LLVM/generated/headers swift build
```

it reports 

> error: missing required module 'LLVM_Utils'

at `import SwiftLLVM_Utils`.

When I build the depending project in Xcode, it reports

> No such module 'SwiftLLVM_Utils'

also at `import SwiftLLVM_Utils`.

My toolchain is the 2024-02-15 trunk snapshot.

This is what my depending package's `Package.swift` looks like:

```swift
// swift-tools-version: 5.9

import Foundation
import PackageDescription

var environment = ProcessInfo.processInfo.environment

var swiftLLVMBindings: Package.Dependency {
    if environment["SWIFT_LLVM_BINDINGS_PATH_TO_LLVM_HEADERS"] != nil && environment["SWIFT_LLVM_BINDINGS_PATH_TO_LLVM_GENERATED_HEADERS"] != nil {
        return .package(url: "https://github.com/apple/swift-llvm-bindings.git", branch: "llvm.org/main")
    } else {
        return .package(path: "/local/copy/with/correct/includes")
    }
}


let package = Package(
    name: "depending-package",
    products: [.library(name: "depending-package", targets: ["depending-package"]),],
    dependencies: [swiftLLVMBindings],
    targets: [
        .target(
            name: "depending-package",
            dependencies: [.product(name: "SwiftLLVM_Utils", package: "swift-llvm-bindings"),],
            swiftSettings: [.interoperabilityMode(.Cxx),]
        ),
        .testTarget(
            name: "depending-packageTests",
            dependencies: ["depending-package"]
        ),
    ]
)
```

What should I do in order to use the project as a dependency?

**Comment by egorzhdan** [comment]
Could you please try adding the same include search paths (`-I ...`) that are passed when building the swift-llvm-bindings package to your depending package as well? As an experiment, you could try passing hardcoded paths in `Package.swift` of your package.

This is how include search paths are configured in this package: https://github.com/apple/swift-llvm-bindings/blob/b9b825218a945e450cbaf740a980284b323e09ca/Package.swift#L9-L35

**Comment by WowbaggersLiquidLunch** [comment]
Thanks, adding include paths moved the build forward. However, there are new errors when building `LLVM_Utils`: 

https://gist.github.com/WowbaggersLiquidLunch/1230b986a18a992740bb09ea90e64702

This is what my `Package.swift` looks like now:

```swift
// swift-tools-version: 5.9

import Foundation
import PackageDescription

var environment = ProcessInfo.processInfo.environment

var swiftLLVMBindings: Package.Dependency {
    if environment["SWIFT_LLVM_BINDINGS_PATH_TO_LLVM_HEADERS"] != nil && environment["SWIFT_LLVM_BINDINGS_PATH_TO_LLVM_GENERATED_HEADERS"] != nil {
        return .package(url: "https://github.com/apple/swift-llvm-bindings.git", branch: "llvm.org/main")
    } else {
        return .package(path: "/local/copy/with/correct/includes")
    }
}

var swiftSettings: [SwiftSetting] {
    let env = ProcessInfo.processInfo.environment
    let llvmHeaderPath = env["SWIFT_LLVM_BINDINGS_PATH_TO_LLVM_HEADERS"] ?? "/path/to/llvm/include"
    let llvmModuleMapPath = "\(llvmHeaderPath)/module.modulemap"
    let llvmGeneratedHeaderPath = env["SWIFT_LLVM_BINDINGS_PATH_TO_LLVM_GENERATED_HEADERS"] ?? "/path/to/build/RelWithDebInfo-Ninja/include"
    
    return [
        .interoperabilityMode(.Cxx),
        .unsafeFlags([
            "-I\(llvmHeaderPath)",
            "-Xcc", "-I\(llvmHeaderPath)",
            "-I\(llvmGeneratedHeaderPath)",
            "-Xcc", "-I\(llvmGeneratedHeaderPath)",
            "-Xcc", "-fmodule-map-file=\(llvmModuleMapPath)",
        ]),
    ]
}

let package = Package(
    name: "depending-package",
    products: [.library(name: "depending-package", targets: ["depending-package"]),],
    dependencies: [swiftLLVMBindings],
    targets: [
        .target(
            name: "depending-package",
            dependencies: [.product(name: "SwiftLLVM_Utils", package: "swift-llvm-bindings"),],
            swiftSettings: swiftSettings
        ),
        .testTarget(
            name: "depending-packageTests",
            dependencies: ["depending-package"]
        ),
    ]
)
```

Could the problem be because the LLVM generated headers are Ninja-generated? Doesn't seem like the reason to me, because the standalone build is find using the same paths, also because afaik llbuild uses Ninja anyway. But I'm not entirely sure.

Or, could this be something with the API notes?

Is there an example project that depends on this project that I can imitate?

**Comment by WowbaggersLiquidLunch** [comment]
Oh ok adding `cxxLanguageStandard: .cxx17` to the depending project got it working.

Thanks so much for the suggestion!
